### ISSUE TITLE
Test existing approaches on Mapillary imagery

### ISSUE THREAD

**Issue by oceanites** [CorrelAid/street-image-classification#16]
Test the different existing approaches on Mapillary imagery

**Comment by adalli13** [comment]
I will have a look at: https://github.com/Intelligent-Vehicle-Perception/Road-Surface-Type-Classification-2
--> not 100% suitable for us as the input data are not only images, but mostly other sensor data, like audio signals

**Comment by adalli13** [comment]
Looking further at: https://github.com/thiagortk/Road-Surface-Classification
