### ISSUE TITLE
Add OSM cycling lanes to make_dataset main function

### ISSUE THREAD

**Issue by adalli13** [CorrelAid/street-image-classification#18]

**Comment by juhule-afk** [comment]
@sn1c @adalli13: Was hattet ihr da im Sinn? Ich dachte man kann einfach "driving" durch "cycling" ersetzen beim get_network-Befehl. Oder worum geht's hier? Hab mir das wohl etwas voreilig zugewiesen :-D

**Comment by juhule-afk** [comment]
Task is about various definitions of cycling lane (and the question which of them was chosen by pyrosm).

**Comment by juhule-afk** [comment]
https://pyrosm.readthedocs.io/en/latest/custom_filter.html#keep-vs-exclude-data-with-custom-filters -> Get all roads that can be cycled. This corresponds to the one procuded by default with get_network("cycling")

**Comment by juhule-afk** [comment]
Conclusion: We'll just use the preset filter get_network("cycling").
