### ISSUE TITLE
Test Mapillary in Python

### ISSUE THREAD

**Issue by dataroo** [CorrelAid/street-image-classification#4]

**Comment by juhule-afk** [comment]
1. Objekt-Segmentierung Polygon - Bild
2. Wie viele Bilder in Stuttgart?
3. Qualitätsstufen?

**Comment by dataroo** [comment]
@juhule-afk : ist es für dich ok, wenn wir das issue hier schließen und lieber einzelne kleinere Issues erstellen? dann ist vllt übersichtlicher, wer woran genau arbeitet :)

**Comment by oceanites** [comment]
Insgesamt gibt es rund 290.000 Bilder in Stuttgart (ausgenommen Panoramabilder).

![Verteilung der Qualitätsstufen für Stuttgart](https://user-images.githubusercontent.com/15113257/116607052-d2334880-a931-11eb-8c6d-f3b680362469.png)
![Verteilung der Aufnahmedaten für Stuttgart](https://user-images.githubusercontent.com/15113257/116607071-d8292980-a931-11eb-8205-3b3029a53a4a.png)

**Comment by juhule-afk** [comment]
@dataroo: Klar, ist prima.
